# Generated by Django 4.2 on 2023-04-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OsSpecs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(default="", max_length=100, unique=True)),
                (
                    "hostByHostname",
                    models.CharField(default="", max_length=100, unique=True),
                ),
                (
                    "hostByAddress",
                    models.JSONField(blank=True, default=dict, max_length=200),
                ),
                (
                    "platform",
                    models.JSONField(blank=True, default=dict, max_length=200),
                ),
                ("latestUpdate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
